from exception import AuthException


class InvalidUserNameException(AuthException):
    pass