from exception import AuthException


class NotLoggedInErrorException(AuthException):
    pass