from exception import AuthException


class UserNameAlreadyExistsException(AuthException):
    pass